name: Submit

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.10"
          cache: poetry
      - name: Install dependencies
        run: poetry install
      - name: Submit tests
        run: |
          mkdir -p build
          poetry run papermill hw1.ipynb build/out.ipynb
        env:
          YOUR_GRADER_KEY_HERE: ${{ secrets.YOUR_GRADER_KEY_HERE }}
